name: advance_text_field
description: an advance text field for flutter, customizable and contain two button for save and make editable text field.
version: 0.0.1
homepage: https://github.com/kumsumit/advance_text_field.git

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
